"""
Django settings for bytenews project.
Generated by 'django-admin startproject' using Django 5.0.
"""

import os
from pathlib import Path

# ---------------------------------
# 📁 Base Directory
# ---------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------
# 🔐 Security
# ---------------------------------
SECRET_KEY = 'django-insecure-mcj70_@8n!mabhok#b6xbtjf=@uq-kuub2@@26(912@j%^%&iv'
DEBUG = True
ALLOWED_HOSTS = []

# ---------------------------------
# 🧩 Installed Apps
# ---------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your custom apps
    'users.apps.UsersConfig',
    'news',
    'rest_framework',
    'debug_toolbar',
]

# ---------------------------------
# ⚙️ Middleware
# ---------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
INTERNAL_IPS = [
    "127.0.0.1",
]


# ---------------------------------
# 🌐 Root URL Configuration
# ---------------------------------
ROOT_URLCONF = 'bytenews.urls'

# ---------------------------------
# 🧠 Templates
# ---------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'users'],  # ensure templates are recognized
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ---------------------------------
# 🚀 WSGI
# ---------------------------------
WSGI_APPLICATION = 'bytenews.wsgi.application'

# ---------------------------------
# 🗄️ Database
# ---------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------------
# 🔐 Password Validators
# ---------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------------------------------
# 🌍 Internationalization
# ---------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------------------------------
# 🔗 Login/Logout Redirection
# ---------------------------------
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ---------------------------------
# 🗂️ Static & Media Files
# ---------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "users" / "static",  # Optional: include app-specific static
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # for collectstatic (useful in production)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # where gTTS audio files will be stored

# ---------------------------------
# 🔑 Default Primary Key
# ---------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,  # 👈 You can adjust the page size
}


# ✅ In-memory cache for development
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
