# Generated by Django 5.2.4 on 2025-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_userpreference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
