# Generated by Django 5.2.4 on 2025-07-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary_helpful',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_not_helpful',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
