# Generated by Django 5.2.4 on 2025-08-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='readinghistory',
            options={'ordering': ['-read_at'], 'verbose_name': 'Reading History', 'verbose_name_plural': 'Reading Histories'},
        ),
    ]
